name: test
base: basic_config.yaml

render:
  enable_gl: true
  title: WoBingWang
  clearcolor: [1.0, 1.0, 1.0, 1.0]
  camera:
    eye: [5.0, 3, 5.0]
    center: [0.0, 0.0, 0.0]
    up: [0.0, 1.0, 0.0]

load:
  rigidbody:
    cfg: 
      # - name: test.obj
      #   scale: [2.0, 2.0, 2.0]
      #   position: [0.0, 0.0, 0.0]
      #   velocity: [0.0, 0.0, 0.0]
      #   acceleration: [0.0, 0.0, 0.0]
      #   orientation: [1.0, 0.0, 0.0, 0.0]
      #   angular_velocity: [0.0, 0.0, 1.0]
      #   angular_acceleration: [0.0, 0.0, 0.0]
      #   mass: 5.0
      # - name: square.obj
      #   scale: [1.0, 1.0, 1.0]
      #   position: [0.0, 0.0, 0.0]
      #   velocity: [0.0, 0.0, 0.0]
      #   acceleration: [0.0, 0.0, 0.0]
      #   orientation: [1.0, 0.0, 0.0, 0.0]
      #   angular_velocity: [0.0, 1.0, 1.0]
      #   angular_acceleration: [0.0, 0.0, 0.0]
      #   mass: 1.0
  fluid:
    base: basic_PICFLIP.yaml
    type: PICFLIP
    cfg: 
      - init: cube # fromfile or cube
        name: test.obj # this required for fromfile
        center: [0.0, 3.0, 0.0]
        density: 0.04

        scale: [0.8, 0.8, 0.8]
        num: [40, 40, 40]
        # num: [10, 20, 10]
        radius: 0.002 # these three required for cube
        mass: 6e-3
        rho: 1000.0
  cloth: 
    cfg:
      - init: square # fromfile or square
        name: test.cloth
        scale: [3, 3]
        delta_y: 0.8
        num: [80, 80]
        height: -0.62
        mass: 0.1
        radius: 0.05
        ks: [1000.0, 1000.0, 1000.0]
        kd: [0, 0, 0]
        damping: 0.0015
        wetting_speed: 1.0
        fix_corner: true
      - init: square # fromfile or square
        name: test.cloth
        scale: [3, 3]
        delta_y: -0.8
        num: [80, 80]
        height: 1.62
        mass: 0.1
        radius: 0.05
        ks: [1000.0, 1000.0, 1000.0]
        kd: [0, 0, 0]
        damping: 0.0015
        wetting_speed: 1.0
        fix_corner: true
  wall:
    cfg:
      # - type: triangle
      #   pos1: [-30, -10, -30]
      #   pos2: [-30, -10, 30]
      #   pos3: [30, -10, 30]
      #   thickness: 0.3
      #   restitution: 0.1
      #   friction: 0.9
      # - type: triangle
      #   pos1: [30, -10, -30]
      #   pos2: [-30, -10, -30]
      #   pos3: [30, -10, 30]
      #   thickness: 0.3
      #   restitution: 0.1
      #   friction: 0.9
      # - type: sphere
      #   center: [-5, -7, 0]
      #   radius: 5
      # - type: triangle
      #   pos1: [0, -5, 10]
      #   pos2: [0, -15, -10]
      #   pos3: [0, -15, 10]
      #   thickness: 0.1
      #   restitution: 0.9
      #   friction: 0.9
      # - type: triangle
      #   pos1: [0, -5, 10]
      #   pos2: [0, -5, -10]
      #   pos3: [0, -15, -10]
      #   thickness: 0.1
      #   restitution: 0.9
      #   friction: 0.9

        

video:
  fps: 20
  sps: 60
  length: 6

simulation:
  box: 
    min: [-1.6, -2.2, -1.6]
    max: [1.6, 4.2, 1.6]
  resolution: [60, 120, 60]

cuda:
  enabled: true

blender:
  enabled: true