# global
name: test
base: basic_config.yaml

render:
  title: WoBingWang
  clearcolor: [1.0, 1.0, 1.0, 1.0]

load:
  rigidbody:
    cfg: 
      # - name: test.obj
      #   scale: [2.0, 2.0, 2.0]
      #   position: [0.0, 0.0, 0.0]
      #   velocity: [0.0, 0.0, 0.0]
      #   acceleration: [0.0, 0.0, 0.0]
      #   orientation: [1.0, 0.0, 0.0, 0.0]
      #   angular_velocity: [0.0, 0.0, 1.0]
      #   angular_acceleration: [0.0, 0.0, 0.0]
      #   mass: 5.0
      # - name: square.obj
      #   scale: [1.0, 1.0, 1.0]
      #   position: [0.0, 0.0, 0.0]
      #   velocity: [0.0, 0.0, 0.0]
      #   acceleration: [0.0, 0.0, 0.0]
      #   orientation: [1.0, 0.0, 0.0, 0.0]
      #   angular_velocity: [0.0, 1.0, 1.0]
      #   angular_acceleration: [0.0, 0.0, 0.0]
      #   mass: 1.0
  fluid:
    cfg: 
      - init: cube # fromfile or cube
        name: test.fluid # this required for fromfile
        # scale: [1.0, 1.0, 1.0]
        # num: [50, 50, 50]
        scale: [0.4, 0.8, 0.4]
        num: [20, 40, 20]
        radius: 0.01 # these three required for cube
        mass: 6e-6
        rho: 1000.0
        

video:
  fps: 30
  sps: 30
  length: 5

simulation:
  box: 
    min: [-3.0, -2.0, -3.0]
    max: [2.0, 2.0, 2.0]

cuda:
  enabled: true